[tools]
agy = "latest"
bun = "latest"
codex = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
uv = "latest"
"npm:cline" = "latest"
"npm:wrangler" = "latest"


[settings]
experimental = true
not_found_auto_install = false
python.venv_stdlib = false

[settings.upgrade]
auto_prune = false
