name = "ssh"
main = "worker.js"
compatibility_date = "2024-09-01"

# KV Namespace Binding
[[kv_namespaces]]
binding = "SSH_KV"
# پس از ساخت KV در داشبورد یا با دستور npx wrangler kv namespace create SSH_KV
# شناسه (id) تولید شده را اینجا قرار دهید:
id = "8de29af45b394d8aaa43f2a111992240"
